global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend-metrics'
    static_configs:
      - targets: ['backend:3001']


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
        
rule_files:
  - "alert_rules.yml"


